version: '3.7'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    # networks:
    #   - airflow-network

  webserver:
    image: apache/airflow:2.2.3
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@ip-172-31-38-55.sa-east-1.compute.internal/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
      AIRFLOW__WEBSERVER__SECRET_KEY: 58d7e1bbf5c51d820a8fc73bc3ab2283
    volumes:
      - ./dags:/opt/airflow/dags    
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 500M
    # depends_on:
    #   - postgres
    command: webserver
    # networks:
    #   - airflow-network


  scheduler:
    image: apache/airflow:2.2.3
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@ip-172-31-38-55.sa-east-1.compute.internal/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
      AIRFLOW__WEBSERVER__SECRET_KEY: 58d7e1bbf5c51d820a8fc73bc3ab2283
    volumes:
      - ./dags:/opt/airflow/dags
    # depends_on:
    #   - postgres
    command: scheduler
    # networks:
    #   - airflow-network

  init:
    image: apache/airflow:2.2.3
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@ip-172-31-38-55.sa-east-1.compute.internal:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
      AIRFLOW__WEBSERVER__SECRET_KEY: 58d7e1bbf5c51d820a8fc73bc3ab2283
    volumes:
      - ./dags:/opt/airflow/dags
    # networks:
    #   - airflow-network
    # depends_on:
    #   - postgres
    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
    

# networks:
#   airflow-network:
#     driver: bridge
